[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"

[profile.default.resolc]
resolc_compile = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
